#!/usr/bin/env python3


import argparse
import os
import platform
import psutil
import sys


MACHINE = platform.machine()
try:
    ARCH = {
            'x86_64': 'amd64',
            'i386': 'i386'
        }[MACHINE]
except KeyError as e:
    print(f'Unsupported machine type {MACHINE}')
# Defaults
CORES = psutil.cpu_count(logical=False)
DIST = 'unstable'
IMAGEDIR = os.environ.get('IMAGEDIR', '/var/cache/qemu-sbuild')


def main():
    # init options
    parser = argparse.ArgumentParser(description='QEMU-based sbuild launcher')

    parser.add_argument('--arch', action='store', default=ARCH)
    parser.add_argument('--clean', action='store_true')
    parser.add_argument('-d', '--dist', action='store', default=DIST)
    parser.add_argument('--image', action='store')
    parser.add_argument('--autopkgtest-debug', action='store_true')
    parser.add_argument('--ram', metavar='MiB', action='store', default=8192)
    parser.add_argument('--cpus', metavar='cpus', action='store', default=CORES)
    parser.add_argument('--noexec', action='store_true')

    parsed_args, unparsed_args = parser.parse_known_args()

    if parsed_args.image:
        image = parsed_args.image
    else:
        image = os.path.join(IMAGEDIR, f'{parsed_args.dist}-autopkgtest-{ARCH}')
        if parsed_args.clean:
            image += '-clean'
        image += '.img'
    qemu = f'qemu-system-{MACHINE}'

    args = [
            'sbuild',
            '--arch',                           parsed_args.arch,
            '--dist',                           parsed_args.dist,
            '--purge-build=never',
            '--purge-deps=never',
            '--chroot-mode=autopkgtest',
            '--autopkgtest-virt-server=qemu',
            '--autopkgtest-virt-server-opt',    '--overlay-dir=/tmp',
            '--autopkgtest-virt-server-opt',    f'--qemu-command={qemu}',
            '--autopkgtest-virt-server-opt',    f'--ram-size={parsed_args.ram}',
            '--autopkgtest-virt-server-opt',    f'--cpus={parsed_args.cpus}',
            '--autopkgtest-virt-server-opt',    image,
            # Worarkound -- dose can hang stuff in a qemu VM
            '--bd-uninstallable-explainer',     'apt',
        ]
    if parsed_args.autopkgtest_debug:
        args += ['--autopkgtest-virt-server-opt', '--debug']

    args += unparsed_args

    print(' '.join(str(a) for a in args))
    if not parsed_args.noexec:
        os.execvp(args[0], args)


if __name__ == '__main__':
    main()
