#!/bin/bash
# SPDX-License-Identifier: BSD-3-Clause
# Author: Christian Kastner <ckk@kvr.at>


set -e
umask 0022


VMROOT="$1"
if [ -z "$VMROOT" ]
then
	echo "$0 expects the mounted root of the VM as first argument." >&2
	exit 1
elif ! mountpoint -q "$VMROOT"
then
	echo "$VMROOT is not a mountpoint." >&2
	exit 1
fi


echo "### Customizing base image ###"

if [ -n "$QSC_SKEL" ]
then
	echo "Copying contents of $QSC_SKEL"
	if [ ! -d "$QSC_SKEL" ]
	then
		echo "$QSC_SKEL is not a directory." >&2
		exit 1
	fi
	cp $QSC_SKEL/. $VMROOT/root
fi

if [ -n "$QSC_INSTALL_PACKAGES" ]
then
	echo "Installing additional packages"
	chroot $VMROOT apt-get install --quiet --assume-yes $QSC_INSTALL_PACKAGES
fi

if [ -n "$QSC_EXTRA_DEBS" ]
then
	echo "Installing extra .debs"
	VMTMP=`mktemp -d -p $VMROOT`
	cp -t $VMTMP $QSC_EXTRA_DEBS
	chroot $VMROOT dpkg --recursive -i `basename $VMTMP`
	chroot $VMROOT apt-get update
	rm -rf $VMTMP
fi

echo "Updating GRUB menu"
echo "GRUB_TIMEOUT=1" >> $VMROOT/etc/default/grub
chroot $VMROOT update-grub

# Mount point for a shared folder, if the VM is launched with one
echo "Adding 9p to initramfs"
echo -e "9p\n9pnet\n9pnet_virtio" >> $VMROOT/etc/initramfs-tools/modules
chroot $VMROOT update-initramfs -u
echo "Adding shared folder to fstab"
mkdir -m 755 $VMROOT/shared
echo "qlaunch /shared 9p trans=virtio,version=9p2000.L,auto,nofail 0 0" >> $VMROOT/etc/fstab

echo "### Customization of base image complete. ###"
